sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    access-key-id:
    access-key-secret:
    bucket-name: bucketname-tale
    endpoint: oss-cn-beijing.aliyuncs.com
  redis:
    host: 192.168.32.129
    port: 6379
    password: wyt516817
    database: 1
  wechat:
    appid: wx20cc78c2b061833f
    secret: 262c67d86f00e56dcd080b337f64a7b0
  shop:
    address: 北京市海淀区上地十街10号
  baidu:
    ak: sENdH9a2PZL8Irj2bNmUEkSKymLYcNwy